# Generated by Django 4.2.21 on 2026-06-07 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='last_username_change',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
