# Generated by Django 4.2.21 on 2026-06-24 15:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('venues', '0001_initial'),
        ('accounts', '0005_ownerregistrationrequest'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffprofile',
            name='venue',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='profile_staff_members', to='venues.venue'),
        ),
    ]
