# Generated by Django 4.2.21 on 2026-05-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        ('bookings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('category', models.CharField(blank=True, choices=[('DRINK', 'Drink'), ('FOOD', 'Food'), ('EQUIPMENT', 'Equipment'), ('RENTAL', 'Rental'), ('OTHER', 'Other')], max_length=20, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='service_items/')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock', models.IntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='venues.venue')),
            ],
            options={
                'db_table': 'service_item',
            },
        ),
        migrations.CreateModel(
            name='BookingService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services_ordered', to='bookings.booking')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_items', to='services.serviceitem')),
            ],
            options={
                'db_table': 'booking_service',
            },
        ),
    ]
