from django.urls import path

from .views import (
    AdminRegistrationRequestApproveView,
    AdminRegistrationRequestDetailView,
    AdminRegistrationRequestListView,
    AdminRegistrationRequestRejectView,
    AdminFieldCreateView,
    AdminVenueFieldDeleteView,
    AdminVenueFieldListView,
    AdminVenueFieldToggleView,
    AdminVenueFieldUpdateView,
    AdminVenueCreateView,
    AdminVenueDeactivateView,
    AdminVenueDetailView,
    AdminVenueListView,
    AdminVenueRestoreView,
    AdminVenueSoftDeleteView,
    AdminVenueUpdateView,
    OwnerFieldCreateView,
    OwnerFieldListView,
    OwnerPriceRuleCreateView,
    OwnerPriceRuleListView,
    OwnerPriceRuleUpdateView,
    OwnerPriceRuleDeleteView,
    OwnerVenueCreateView,
    OwnerVenueListView,
)

app_name = 'venues'

urlpatterns = [
    path('admin/venues/', AdminVenueListView.as_view(), name='admin_venue_list'),
    path('admin/venues/create/', AdminVenueCreateView.as_view(), name='admin_venue_create'),
    path(
        'admin/venues/<int:venue_id>/fields/',
        AdminVenueFieldListView.as_view(),
        name='admin_venue_field_list',
    ),
    path(
        'admin/venues/<int:venue_id>/fields/create/',
        AdminFieldCreateView.as_view(),
        name='admin_venue_field_create',
    ),
    path(
        'admin/venues/<int:venue_id>/fields/<int:pk>/edit/',
        AdminVenueFieldUpdateView.as_view(),
        name='admin_venue_field_update',
    ),
    path(
        'admin/venues/<int:venue_id>/fields/<int:pk>/toggle/',
        AdminVenueFieldToggleView.as_view(),
        name='admin_venue_field_toggle',
    ),
    path(
        'admin/venues/<int:venue_id>/fields/<int:pk>/delete/',
        AdminVenueFieldDeleteView.as_view(),
        name='admin_venue_field_delete',
    ),
    path(
        'admin/venues/<int:venue_pk>/fields/create/',
        AdminFieldCreateView.as_view(),
        name='admin_field_create',
    ),
    path('admin/venues/<int:pk>/', AdminVenueDetailView.as_view(), name='admin_venue_detail'),
    path('admin/venues/<int:pk>/edit/', AdminVenueUpdateView.as_view(), name='admin_venue_update'),
    path('admin/venues/<int:pk>/deactivate/', AdminVenueDeactivateView.as_view(), name='admin_venue_deactivate'),
    path('admin/venues/<int:pk>/delete/', AdminVenueSoftDeleteView.as_view(), name='admin_venue_delete'),
    path('admin/venues/<int:pk>/restore/', AdminVenueRestoreView.as_view(), name='admin_venue_restore'),
    path(
        'admin/venue-requests/',
        AdminRegistrationRequestListView.as_view(),
        name='admin_venue_request_list',
    ),
    path(
        'admin/venue-requests/<int:pk>/',
        AdminRegistrationRequestDetailView.as_view(),
        name='admin_venue_request_detail',
    ),
    path(
        'admin/venue-requests/<int:pk>/approve/',
        AdminRegistrationRequestApproveView.as_view(),
        name='admin_venue_request_approve',
    ),
    path(
        'admin/venue-requests/<int:pk>/reject/',
        AdminRegistrationRequestRejectView.as_view(),
        name='admin_venue_request_reject',
    ),
    path(
        'admin/registration-requests/',
        AdminRegistrationRequestListView.as_view(),
        name='admin_registration_request_list',
    ),
    path(
        'admin/registration-requests/<int:pk>/',
        AdminRegistrationRequestDetailView.as_view(),
        name='admin_registration_request_detail',
    ),
    path(
        'admin/registration-requests/<int:pk>/approve/',
        AdminRegistrationRequestApproveView.as_view(),
        name='admin_registration_request_approve',
    ),
    path(
        'admin/registration-requests/<int:pk>/reject/',
        AdminRegistrationRequestRejectView.as_view(),
        name='admin_registration_request_reject',
    ),
    path(
        'owner/venues/',
        OwnerVenueListView.as_view(),
        name='owner_venue_list',
    ),
    path(
        'owner/venues/',
        OwnerVenueListView.as_view(),
        name='venue_list',
    ),
    path(
        'owner/venues/create/',
        OwnerVenueCreateView.as_view(),
        name='owner_venue_create',
    ),
    path(
        'owner/venues/create/',
        OwnerVenueCreateView.as_view(),
        name='venue_create',
    ),
    path(
        'owner/venues/<int:pk>/fields/',
        OwnerFieldListView.as_view(),
        name='venue_detail',
    ),
    path(
        'owner/venues/<int:venue_pk>/fields/',
        OwnerFieldListView.as_view(),
        name='owner_field_list',
    ),
    path(
        'owner/venues/<int:venue_pk>/fields/create/',
        OwnerFieldCreateView.as_view(),
        name='owner_field_create',
    ),
    path(
        'owner/fields/<int:field_pk>/price-rules/',
        OwnerPriceRuleListView.as_view(),
        name='owner_price_rule_list',
    ),
    path(
        'owner/fields/<int:field_pk>/price-rules/create/',
        OwnerPriceRuleCreateView.as_view(),
        name='owner_price_rule_create',
    ),
    path(
        'owner/price-rules/<int:pk>/edit/',
        OwnerPriceRuleUpdateView.as_view(),
        name='owner_price_rule_edit',
    ),
    path(
        'owner/price-rules/<int:pk>/delete/',
        OwnerPriceRuleDeleteView.as_view(),
        name='owner_price_rule_delete',
    ),
]
