# Generated by Django 4.2.21 on 2026-06-30

from django.db import migrations
from django.utils import timezone


def _existing_tables(schema_editor):
    return set(schema_editor.connection.introspection.table_names())


def _existing_columns(schema_editor, table_name):
    with schema_editor.connection.cursor() as cursor:
        return {
            column.name
            for column in schema_editor.connection.introspection.get_table_description(
                cursor,
                table_name,
            )
        }


def _clone_model_field(model, field_name, default=None):
    field = model._meta.get_field(field_name).clone()
    field.set_attributes_from_name(field_name)
    field.model = model
    if default is not None:
        field.default = default
    return field


def _add_field_if_missing(apps, schema_editor, model, field_name, default=None):
    columns = _existing_columns(schema_editor, model._meta.db_table)
    field = _clone_model_field(model, field_name, default=default)
    if field.column not in columns:
        schema_editor.add_field(model, field)


def sync_singular_payment_tables(apps, schema_editor):
    """Bring existing singular payment tables in line with the payment models."""
    Promotion = apps.get_model('payments', 'Promotion')
    Payment = apps.get_model('payments', 'Payment')
    Invoice = apps.get_model('payments', 'Invoice')

    existing = _existing_tables(schema_editor)
    for model in (Promotion, Payment, Invoice):
        if model._meta.db_table not in existing:
            schema_editor.create_model(model)
            existing.add(model._meta.db_table)

    _add_field_if_missing(apps, schema_editor, Payment, 'created_at', default=timezone.now)
    _add_field_if_missing(apps, schema_editor, Payment, 'updated_at', default=timezone.now)
    _add_field_if_missing(apps, schema_editor, Invoice, 'subtotal_amount')
    _add_field_if_missing(apps, schema_editor, Invoice, 'total_amount')
    _add_field_if_missing(apps, schema_editor, Invoice, 'created_at', default=timezone.now)
    _add_field_if_missing(apps, schema_editor, Invoice, 'updated_at', default=timezone.now)
    _add_field_if_missing(apps, schema_editor, Promotion, 'is_active')


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(sync_singular_payment_tables, migrations.RunPython.noop),
    ]
