# Generated by Django 4.2.21 on 2026-06-30 14:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0002_alter_payment_booking_alter_wallet_user'),
        ('payments', '0004_sync_singular_payment_tables'),
    ]

    operations = [
    ]
