# Generated by Django 4.2.21 on 2026-05-25 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Booking',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('booking_date', models.DateField()),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('PAID', 'Paid'), ('WAITING', 'Waiting'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('booking_channel', models.CharField(choices=[('WEB', 'Web'), ('WALKIN', 'Walk-in')], default='WEB', max_length=10)),
                ('total_amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('payment_deadline', models.DateTimeField(blank=True, null=True)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'booking',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BookingPackage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('package_type', models.CharField(choices=[('SINGLE', 'Single'), ('RECURRING', 'Recurring')], max_length=20)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('refund_amount_applied', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
            options={
                'db_table': 'booking_package',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SlotLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('booking_date', models.DateField()),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('lock_session_id', models.CharField(max_length=255)),
                ('expires_at', models.DateTimeField()),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_slot_locks', to=settings.AUTH_USER_MODEL)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_locks', to='venues.field')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slot_locks', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'slot_lock',
            },
        ),
        migrations.CreateModel(
            name='BookingSlot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='slots', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_slot',
            },
        ),
        migrations.CreateModel(
            name='BookingRecurrenceDay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField(help_text='0=Monday, 6=Sunday')),
                ('booking_package', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recurrence_days', to='bookings.bookingpackage')),
            ],
            options={
                'db_table': 'booking_recurrence_day',
            },
        ),
        migrations.CreateModel(
            name='BookingPromotion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('discount_amount_applied', models.DecimalField(decimal_places=2, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promotions_applied', to='bookings.booking')),
            ],
            options={
                'db_table': 'booking_promotion',
            },
        ),
    ]
