# Generated by Django 4.2.21 on 2026-05-25 10:23

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('venues', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0001_initial'),
        ('payments', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='bookingpromotion',
            name='promotion',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_applications', to='payments.promotion'),
        ),
        migrations.AddField(
            model_name='bookingpackage',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='booking_packages', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='booking_package',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='bookings.bookingpackage'),
        ),
        migrations.AddField(
            model_name='booking',
            name='field',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.field'),
        ),
        migrations.AddField(
            model_name='booking',
            name='venue',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bookings', to='venues.venue'),
        ),
        migrations.AddIndex(
            model_name='slotlock',
            index=models.Index(fields=['field', 'booking_date', 'start_time', 'end_time'], name='slot_lock_field_i_7792cd_idx'),
        ),
        migrations.AddIndex(
            model_name='bookingslot',
            index=models.Index(fields=['booking', 'start_time'], name='booking_slo_booking_d8ca2e_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='bookingpromotion',
            unique_together={('booking', 'promotion')},
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['field', 'booking_date'], name='booking_field_i_1ca824_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['venue', 'booking_date'], name='booking_venue_i_25ecf6_idx'),
        ),
        migrations.AddIndex(
            model_name='booking',
            index=models.Index(fields=['status'], name='booking_status_b99f68_idx'),
        ),
    ]
