# Generated by Codex on 2026-05-27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slotlock',
            name='status',
            field=models.CharField(
                choices=[
                    ('ACTIVE', 'Active'),
                    ('EXPIRED', 'Expired'),
                    ('RELEASED', 'Released'),
                ],
                default='ACTIVE',
                max_length=20,
            ),
        ),
    ]
