# Generated by Django 4.2.21 on 2026-05-25 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
            ],
            options={
                'db_table': 'sport',
            },
        ),
        migrations.CreateModel(
            name='Venue',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, null=True)),
                ('address', models.CharField(max_length=500)),
                ('latitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('longitude', models.DecimalField(blank=True, decimal_places=7, max_digits=10, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('is_deleted', models.BooleanField(default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venues', to='accounts.ownerprofile')),
            ],
            options={
                'db_table': 'venue',
            },
        ),
        migrations.CreateModel(
            name='VenuePolicy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancel_before_hours', models.IntegerField()),
                ('refund_percent', models.DecimalField(decimal_places=2, max_digits=5)),
                ('venue', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='policy', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_policy',
            },
        ),
        migrations.CreateModel(
            name='VenueImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='venue_images/')),
                ('is_thumbnail', models.BooleanField(default=False)),
                ('sort_order', models.IntegerField(default=0)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_image',
                'ordering': ['sort_order'],
            },
        ),
        migrations.CreateModel(
            name='FieldType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=100, unique=True)),
                ('icon', models.CharField(blank=True, max_length=50, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('player_count', models.IntegerField()),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('sport', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_types', to='venues.sport')),
            ],
            options={
                'db_table': 'field_type',
                'unique_together': {('sport', 'name')},
            },
        ),
        migrations.CreateModel(
            name='Field',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('surface_type', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('status', models.CharField(default='ACTIVE', max_length=20)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='venues.fieldtype')),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='venues.venue')),
            ],
            options={
                'db_table': 'field',
            },
        ),
        migrations.CreateModel(
            name='VenueOperatingHour',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weekday', models.SmallIntegerField(help_text='0=Monday, 6=Sunday')),
                ('open_time', models.TimeField()),
                ('close_time', models.TimeField()),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operating_hours', to='venues.venue')),
            ],
            options={
                'db_table': 'venue_operating_hour',
                'unique_together': {('venue', 'weekday')},
            },
        ),
        migrations.CreateModel(
            name='FieldPriceRule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('day_of_week', models.SmallIntegerField(blank=True, help_text='Null = tất cả các ngày', null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('price_per_hour', models.DecimalField(decimal_places=2, max_digits=10)),
                ('start_date', models.DateField(blank=True, null=True)),
                ('end_date', models.DateField(blank=True, null=True)),
                ('priority', models.IntegerField(default=0)),
                ('is_holiday', models.BooleanField(default=False)),
                ('special_event', models.CharField(blank=True, max_length=255, null=True)),
                ('field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='price_rules', to='venues.field')),
            ],
            options={
                'db_table': 'field_price_rule',
                'indexes': [models.Index(fields=['field', 'day_of_week', 'start_time'], name='field_price_field_i_cce1a9_idx')],
            },
        ),
    ]
