# Generated by Django 4.2.21 on 2026-06-30 04:42

from django.conf import settings
import django.core.serializers.json
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0007_userrole_unique_user_role'),
        ('venues', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerVenueRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('CREATE', 'Tạo cơ sở'), ('UPDATE', 'Cập nhật cơ sở'), ('DELETE', 'Hủy cơ sở')], max_length=20)),
                ('payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=20)),
                ('reason', models.TextField(blank=True)),
                ('admin_note', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='owner_venue_requests', to=settings.AUTH_USER_MODEL)),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_owner_venue_requests', to=settings.AUTH_USER_MODEL)),
                ('target_venue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_venue_requests', to='venues.venue')),
            ],
            options={
                'db_table': 'owner_venue_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='FieldCreationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('capacity', models.IntegerField(blank=True, null=True)),
                ('surface_type', models.CharField(blank=True, max_length=50, null=True)),
                ('length', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('width', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True)),
                ('field_status', models.CharField(choices=[('ACTIVE', 'Hoạt động'), ('MAINTENANCE', 'Bảo trì'), ('INACTIVE', 'Ngừng hoạt động')], default='ACTIVE', max_length=20)),
                ('pricing_payload', models.JSONField(blank=True, default=dict, encoder=django.core.serializers.json.DjangoJSONEncoder)),
                ('status', models.CharField(choices=[('PENDING', 'Đang chờ'), ('APPROVED', 'Đã duyệt'), ('REJECTED', 'Đã từ chối')], default='PENDING', max_length=20)),
                ('reject_reason', models.TextField(blank=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('field_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='field_creation_requests', to='venues.fieldtype')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_creation_requests', to='accounts.ownerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_field_creation_requests', to=settings.AUTH_USER_MODEL)),
                ('venue', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_creation_requests', to='venues.venue')),
            ],
            options={
                'db_table': 'field_creation_request',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='VenueRegistrationRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('venue_name', models.CharField(max_length=255)),
                ('venue_address', models.CharField(max_length=500)),
                ('venue_note', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('APPROVED', 'Approved'), ('REJECTED', 'Rejected'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('rejection_reason', models.TextField(blank=True)),
                ('approved_venue', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='registration_request', to='venues.venue')),
                ('owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='venue_registration_requests', to='accounts.ownerprofile')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_venue_registration_requests', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'venue_registration_request',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status'], name='venue_regis_status_cb81a7_idx'), models.Index(fields=['owner', 'status'], name='venue_regis_owner_i_5e0694_idx'), models.Index(fields=['created_at'], name='venue_regis_created_b1f440_idx')],
            },
        ),
        migrations.AddConstraint(
            model_name='venueregistrationrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED', 'CANCELLED'])), name='venue_registration_request_status_valid'),
        ),
        migrations.AddIndex(
            model_name='ownervenuerequest',
            index=models.Index(fields=['status'], name='owner_venue_status_b1caa4_idx'),
        ),
        migrations.AddIndex(
            model_name='ownervenuerequest',
            index=models.Index(fields=['request_type', 'status'], name='owner_venue_request_fd18ea_idx'),
        ),
        migrations.AddIndex(
            model_name='ownervenuerequest',
            index=models.Index(fields=['requested_by', 'status'], name='owner_venue_request_f428b8_idx'),
        ),
        migrations.AddIndex(
            model_name='ownervenuerequest',
            index=models.Index(fields=['created_at'], name='owner_venue_created_5dff97_idx'),
        ),
        migrations.AddConstraint(
            model_name='ownervenuerequest',
            constraint=models.CheckConstraint(check=models.Q(('request_type__in', ['CREATE', 'UPDATE', 'DELETE'])), name='owner_venue_request_type_valid'),
        ),
        migrations.AddConstraint(
            model_name='ownervenuerequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='owner_venue_request_status_valid'),
        ),
        migrations.AddIndex(
            model_name='fieldcreationrequest',
            index=models.Index(fields=['status'], name='field_creat_status_f867d2_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldcreationrequest',
            index=models.Index(fields=['owner', 'status'], name='field_creat_owner_i_e58114_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldcreationrequest',
            index=models.Index(fields=['venue', 'status'], name='field_creat_venue_i_729ba8_idx'),
        ),
        migrations.AddIndex(
            model_name='fieldcreationrequest',
            index=models.Index(fields=['created_at'], name='field_creat_created_dd65c0_idx'),
        ),
        migrations.AddConstraint(
            model_name='fieldcreationrequest',
            constraint=models.CheckConstraint(check=models.Q(('field_status__in', ['ACTIVE', 'MAINTENANCE', 'INACTIVE'])), name='field_creation_request_field_status_valid'),
        ),
        migrations.AddConstraint(
            model_name='fieldcreationrequest',
            constraint=models.CheckConstraint(check=models.Q(('status__in', ['PENDING', 'APPROVED', 'REJECTED'])), name='field_creation_request_status_valid'),
        ),
    ]
